baseURL = "https://ismael.casimpan.com/resume"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "Ismael Casimpan Resume"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
#colorPrimary = "#e3bfb8"
colorPrimary = "#cc9900"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 3
